### ISSUE TITLE
在执行到07步骤中报错了，报错has no attribute 'stdout'，排查不出啥问题导致的

### ISSUE THREAD

**Issue by Jeremy-ZJL** [easzlab/kubeasz#1143]
在07步骤中报错了，has no attribute 'stdout'
```
TASK [cluster-addon : 创建 prom chart 个性化设置] *************************************************************************************************************************************************************************************************************************
task path: /etc/kubeasz/roles/cluster-addon/tasks/prometheus.yml:41
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1139, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'stdout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1176, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'stdout'
fatal: [10.0.0.63]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'stdout'"
}
```

**Comment by gjmzj** [comment]
这个问题已修复，马上要发新版本支持v1.24，还有更新的prometheus 部署
