### ISSUE TITLE
efk question 读写问题

### ISSUE THREAD

**Issue by mrhjx2** [easzlab/kubeasz#231]
+ chown -R elasticsearch:elasticsearch /data
+ ./bin/elasticsearch_logging_discovery
+ exec su elasticsearch -c ./bin/es-docker
[2018-06-14T07:19:33,092][INFO ][o.e.n.Node               ] [elasticsearch-logging-1] initializing ...
[2018-06-14T07:19:39,261][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-logging-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/kubernetes-logging]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.4.jar:5.6.4]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/kubernetes-logging]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.&lt;init&gt;(NodeEnvironment.java:261) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.&lt;init&gt;(Node.java:265) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.&lt;init&gt;(Node.java:245) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.&lt;init&gt;(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.4.jar:5.6.4]
	... 6 more
Caused by: java.io.IOException: failed to obtain lock on /data/nodes/0
	at org.elasticsearch.env.NodeEnvironment.&lt;init&gt;(NodeEnvironment.java:240) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.&lt;init&gt;(Node.java:265) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.&lt;init&gt;(Node.java:245) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.&lt;init&gt;(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.4.jar:5.6.4]
	... 6 more
Caused by: java.io.IOException: No locks available 

drwxr-xr-x 3 1000 1000 19 Jun 14 15:17 es0
drwxr-xr-x 3 1000 1000 19 Jun 14 15:07 es1
drwxr-xr-x 2 root root  6 Jun 14 14:48 es2

1000 uid这个用户 系统不存在的

**Comment by gjmzj** [comment]
报错是目录权限问题，nfs共享目录权限设置成777，试试

**Comment by gjmzj** [comment]
#223 已经有人提issue了，并且给出了方案
需要去nfs服务器上设置如下：
chown nobody:nogroup /data

**Comment by Mrhjx2** [comment]
我找到问题根源了 是nfs系统文件格式问题

**Comment by gjmzj** [comment]
嗯，有时间具体分析下这个文件格式问题，对其他人也能有帮助
