### ISSUE TITLE
部署speaker报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by weixiao122** [easzlab/kubeasz#442]
os：7.5
K8S_VER="v1.11"

在部署speaker的时候一直报错，尝试删除重启还是一样，请问有什么解决方法吗
```
[root@test1 ansible]# kubectl label nodes 192.168.212.196 node-role.kubernetes.io/metallb-speaker=true
node/192.168.212.196 labeled


[root@test1 ansible]# kubectl get pod -n metallb-system 
NAME                        READY     STATUS              RESTARTS   AGE
controller-9c57dbd4-pstjg   1/1       Running             0          4h
speaker-v7r5s               0/1       CrashLoopBackOff    11         34m
speaker-wkp8n               0/1       ContainerCreating   0          10s

[root@test1 prometheus]# kubectl describe  pod -n metallb-system speaker-wkp8n
Name:           speaker-wkp8n
Namespace:      metallb-system
Node:           192.168.212.196/192.168.212.196
Start Time:     Tue, 15 Jan 2019 13:51:46 +0800
Labels:         app=metallb
                component=speaker
                controller-revision-hash=4154930524
                pod-template-generation=2
Annotations:    prometheus.io/port=7472
                prometheus.io/scrape=true
Status:         Running
IP:             192.168.212.196
Controlled By:  DaemonSet/speaker
Containers:
  speaker:
    Container ID:  docker://79dc52f8bfd289e62f80bd504091b14a8356dcfee5909cf80232ea191df1fe9e
    Image:         metallb/speaker:v0.7.3
    Image ID:      docker-pullable://metallb/speaker@sha256:dc13f9c56ca0282d7ea545d71a89fd98c2fa76a1e297d08fd2958821508435ed
    Port:          7472/TCP
    Host Port:     7472/TCP
    Args:
      --port=7472
      --config=config
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 15 Jan 2019 13:52:11 +0800
      Finished:     Tue, 15 Jan 2019 13:52:12 +0800
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      METALLB_NODE_NAME:         (v1:spec.nodeName)
      KUBERNETES_SERVICE_HOST:  {{ MASTER_IP }}
      KUBERNETES_SERVICE_PORT:  {{ KUBE_APISERVER.split(':')[2] }}
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from speaker-token-88tx8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  speaker-token-88tx8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  speaker-token-88tx8
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  node-role.kubernetes.io/metallb-speaker=true
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason   Age               From                      Message
  ----     ------   ----              ----                      -------
  Normal   Pulling  34s               kubelet, 192.168.212.196  pulling image "metallb/speaker:v0.7.3"
  Normal   Pulled   10s               kubelet, 192.168.212.196  Successfully pulled image "metallb/speaker:v0.7.3"
  Normal   Created  9s (x2 over 10s)  kubelet, 192.168.212.196  Created container
  Normal   Started  9s (x2 over 10s)  kubelet, 192.168.212.196  Started container
  Normal   Pulled   9s                kubelet, 192.168.212.196  Container image "metallb/speaker:v0.7.3" already present on machine
  Warning  BackOff  6s (x2 over 7s)   kubelet, 192.168.212.196  Back-off restarting failed container
```

查看日志发现报错
```
[root@test1 prometheus]# kubectl logs -n metallb-system speaker-wkp8n
{"branch":"HEAD","caller":"main.go:63","commit":"69a8379e","msg":"MetalLB speaker starting version 0.7.3 (commit 69a8379e, branch HEAD)","ts":"2019-01-15T05:52:31.004740714Z","version":"0.7.3"}
{"caller":"main.go:98","error":"creating Kubernetes client: host must be a URL or a host:port pair: \"https://{{ MASTER_IP }}:{{ KUBE_APISERVER.split(':')[2] }}\"","msg":"failed to create k8s client","op":"startup","ts":"2019-01-15T05:52:31.005186514Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xf51d26]

goroutine 1 [running]:
go.universe.tf/metallb/internal/k8s.(*Client).Run(0x0, 0xc420059f20, 0x6)
	/go/src/go.universe.tf/metallb/internal/k8s/k8s.go:230 +0x26
main.main()
	/go/src/go.universe.tf/metallb/speaker/main.go:101 +0x9b4
```

**Comment by gjmzj** [comment]
你估计没仔细看安装文档，按照本项目文档来安装吧。
pod的yaml配置里面还有ansible 变量没替换呢。。。

**Comment by weixiao122** [comment]
我是根据项目文档来执行的
1.cat roles/cluster-addon/defaults/main.yml     #修改yml文件
# metallb 自动安装
metallb_install: "yes"
# 模式选择: 二层 "layer2" 或者三层 "bgp"
metallb_protocol: "layer2"
metallb_offline: "metallb_v0.7.3.tar"
metallb_vip_pool: "192.168.212.0/24"

2.再执行安装 ansible-playbook 07.cluster-addon.yml

3.kubectl label nodes 192.168.212.199 node-role.kubernetes.io/metallb-speaker=true   


我是根据项目按照上面的步骤来操作的，这样有问题么，还是我漏了哪些步骤呢，谢谢！
另外我使用kubeasz 集成安装metallb，kubeasz是否有脚本卸载metallb，再重新安装metallb呢，谢谢！

**Comment by hom7** [comment]
也没看懂怎么替换端口

# 部分flannel配置，参考 docs/setup/network-plugin/flannel.md

# 设置flannel 后端
#FLANNEL_BACKEND: "host-gw"
FLANNEL_BACKEND: "vxlan"

#flanneld_image: "quay.io/coreos/flannel:v0.10.0-amd64"
flanneld_image: "easzlab/flannel:v0.11.0-amd64"

# 离线镜像tar包
flannel_offline: "flannel_v0.11.0-amd64.tar"
- name: KUBERNETES_SERVICE_HOST
  value: {{ 192.168.111.1 }}
- name: KUBERNETES_SERVICE_PORT
  value: {{ KUBE_APISERVER.split(':')[2] }}    

   # value: {{ 6443 }} 这样写也是报错
