### ISSUE TITLE
升级efk到6.1.1后，有节点的fluented没法用

### ISSUE THREAD

**Issue by jacky-neo** [easzlab/kubeasz#653]
2019-07-29 06:13:42 +0000 [error]: unexpected error error_class=Errno::EHOSTUNREACH error="Failed to open TCP connection to 10.68.0.1:443 (No route to host - connect(2) for \"10.68.0.1\" port 443)"
  2019-07-29 06:13:42 +0000 [error]: /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
  2019-07-29 06:13:42 +0000 [error]: /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
  2019-07-29 06:13:42 +0000 [error]: /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  2019-07-29 06:13:42 +0000 [error]: /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

**Comment by gjmzj** [comment]
根据你这个日志信息，可能大家都没法定位问题

**Comment by jacky-neo** [comment]
喔，我后来绕开了。刚好这个节点的日志不用记。我把manifests/efk/fluented-es-ds.yml里的nodeSelector注释打开，规避了这个问题。
