### ISSUE TITLE
ansible 在本地设置bin目录权限时发生无权限的问题

### ISSUE THREAD

**Issue by lovepluskaka** [easzlab/kubeasz#807]
执行环境：virtualBox安装 ubuntu
步骤：
  执行 `ansible-playbook 01.prepare.yml`
返回错误信息
  ```TASK [deploy : 本地设置 bin 目录权限] ***********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 1] Operation not permitted: '/etc/ansible/bin'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TUHJIq/ansible_module_file.py\", line 742, in <module>\n    main()\n  File \"/tmp/ansible_TUHJIq/ansible_module_file.py\", line 728, in main\n    result = ensure_directory(path, follow, recurse)\n  File \"/tmp/ansible_TUHJIq/ansible_module_file.py\", line 462, in ensure_directory\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff, expand=False)\n  File \"/tmp/ansible_TUHJIq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1568, in set_fs_attributes_if_different\n  File \"/tmp/ansible_TUHJIq/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1340, in set_mode_if_different\nOSError: [Errno 1] Operation not permitted: '/etc/ansible/bin'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP ******************************************************************************************************************************************************************************
192.168.56.101             : ok=1    changed=0    unreachable=0    failed=0   
192.168.56.102             : ok=1    changed=0    unreachable=0    failed=0   
192.168.56.103             : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```
是否要给ansible配置root用户的权限呢

**Comment by lovepluskaka** [comment]
详细的日志为
```
TASK [deploy : 本地设置 bin 目录权限] ***********************************************************************************************************************************************************
task path: /etc/ansible/roles/deploy/tasks/main.yml:7
Using module file /home/test0/.local/lib/python2.7/site-packages/ansible/modules/files/file.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: test0
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_qruSgF/ansible_module_file.py", line 742, in <module>
    main()
  File "/tmp/ansible_qruSgF/ansible_module_file.py", line 728, in main
    result = ensure_directory(path, follow, recurse)
  File "/tmp/ansible_qruSgF/ansible_module_file.py", line 462, in ensure_directory
    changed = module.set_fs_attributes_if_different(file_args, changed, diff, expand=False)
  File "/tmp/ansible_qruSgF/ansible_modlib.zip/ansible/module_utils/basic.py", line 1568, in set_fs_attributes_if_different
  File "/tmp/ansible_qruSgF/ansible_modlib.zip/ansible/module_utils/basic.py", line 1340, in set_mode_if_different
OSError: [Errno 1] Operation not permitted: '/etc/ansible/bin'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qruSgF/ansible_module_file.py\", line 742, in <module>\n    main()\n  File \"/tmp/ansible_qruSgF/ansible_module_file.py\", line 728, in main\n    result = ensure_directory(path, follow, recurse)\n  File \"/tmp/ansible_qruSgF/ansible_module_file.py\", line 462, in ensure_directory\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff, expand=False)\n  File \"/tmp/ansible_qruSgF/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1568, in set_fs_attributes_if_different\n  File \"/tmp/ansible_qruSgF/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1340, in set_mode_if_different\nOSError: [Errno 1] Operation not permitted: '/etc/ansible/bin'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

**Comment by gjmzj** [comment]
需要root权限运行安装脚本
